# Generated by Django 5.2 on 2025-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_feepayment_feestructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
