from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('student/dashboard/', views.student_dashboard, name='student_dashboard'),
    path('teacher/dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('register/student/', views.register_student, name='register_student'),
    path('register/teacher/', views.register_teacher, name='register_teacher'),
    path('create/schedule/', views.create_schedule, name='create_schedule'),
    path('update/schedule/<int:schedule_id>/', views.update_schedule, name='update_schedule'),
    path('delete/schedule/<int:schedule_id>/', views.delete_schedule, name='delete_schedule'),
    path('student/schedule/', views.student_schedule, name='student_schedule'),
    path('create/assignment/', views.create_assignment, name='create_assignment'),
    path('submit/assignment/<int:assignment_id>/', views.submit_assignment, name='submit_assignment'),
    path('view/submissions/<int:assignment_id>/', views.view_submissions, name='view_submissions'),
    path('grade/submission/<int:submission_id>/', views.grade_submission, name='grade_submission'),
    path('upload/marks/', views.upload_marks, name='upload_marks'),
    path('mark/attendance/', views.mark_attendance, name='mark_attendance'),
    path('view/students/', views.view_students, name='view_students'),
    path('view/teachers/', views.view_teachers, name='view_teachers'),
    path('update/student/<int:student_id>/', views.update_student, name='update_student'),
    path('update/teacher/<int:teacher_id>/', views.update_teacher, name='update_teacher'),
    path('view/student/<int:student_id>/', views.view_student_details, name='view_student_details'),
    path('view/teacher/<int:teacher_id>/', views.view_teacher_details, name='view_teacher_details'),
    path('view/schedules/', views.view_schedules, name='view_schedules'),
    path('student/fee-details/', views.student_fee_details, name='student_fee_details'),
    path('view/student-attendance/<int:student_id>/', views.view_student_attendance, name='view_student_attendance'),
    path('view/student-marks/<int:student_id>/', views.view_student_marks, name='view_student_marks'),
    path('view/student-list/', views.view_student_list, name='view_student_list'),
    path('manage/fee-structure/', views.manage_fee_structure, name='manage_fee_structure'),
    path('record/fee-payment/', views.record_fee_payment, name='record_fee_payment'),
    path('change-password/', views.change_password, name='change_password'),
] 